# Docker Compose untuk development/testing
version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - redis
    volumes:
      - ./redis_password.txt:/run/secrets/redis_password:ro
    networks:
      - app-network

  redis:
    image: redis:7-alpine
    command: sh -c 'redis-server --requirepass "$$(cat /run/secrets/redis_password)"'
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
      - ./redis_password.txt:/run/secrets/redis_password:ro
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  redis-data: