# Docker Compose untuk development/testing
version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - redis
    environment:
      - REDIS_PASSWORD=myredispassword123
    networks:
      - app-network

  redis:
    image: redis:7-alpine
    command: redis-server --requirepass myredispassword123
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  redis-data: